### ISSUE TITLE
can dont reset expression after model_proxy.speak ?

### ISSUE THREAD

**Issue by ferdinandbr** [RaSan147/pixi-live2d-display#1]
hello! I'm having a problem due to a customizable model, where I have to pass hair, clothing, etc. parameters to an expression. When the model is loaded I can make the "outfit" expression stick, but after the model_proxy.speak it resets the expression. Do you have any idea how I can resolve this?

**Comment by RaSan147** [comment]
I'll check on it and if possible make a Expression_No_reset=false argument

**Comment by RaSan147** [comment]
okk lets make a breaking change

motio(group: string, index: number, priority: MotionPriority, `sound?: string, volume?:number, expression?: number | string, resetExpression?:boolean`)

lets make the rest of the parts as {sound?: string, volume?:number, expression?: number | string, resetExpression?:boolean} optional args. This way it will be easier to improve it and add as many options as we want.

**Comment by RaSan147** [comment]
@ferdinandbr check the latest update and js link

**Comment by ferdinandbr** [comment]
Thank you very much for your help, it worked great!

**Comment by RaSan147** [comment]
Thanks to you i found out the last version had a major bug (moved from a fork's fork to a fork from original   and missed updating some files)
