### ISSUE TITLE
Could you please provide a sample video to demonstrate the lip-syncing capability?

### ISSUE THREAD

**Issue by lvyonghuan** [RaSan147/pixi-live2d-display#13]
I work with Go programming language, and I'm not very familiar with the use of TypeScript and similar technologies. I'm currently involved in some related projects, and I would like to see the lip-syncing capabilities of this fork.

It would be ideal if it could read slightly longer phrases to showcase the ability.

Thanks.

**Comment by RaSan147** [comment]
It reads from audio file... not text. the longer the audio file, the longer it speaks. (its my 1st TS project too, I don't even have the basics, using JS knowledge to add lipsync capability)

Check the readme... it has an example showing how to play with JS

**Comment by RaSan147** [comment]
you can use edge-tts (python) in the back end to generate text to speech (or some AI tools to do so and send the server (or give static links to your project)
