### ISSUE TITLE
Load moc file, throw Unknown settings format.

### ISSUE THREAD

**Issue by weihaopeng** [RaSan147/pixi-live2d-display#16]
I try to add model from https://github.com/Eikanya/Live2d-model/tree/master/%E9%AD%82%E5%99%A8%E5%AD%A6%E9%99%A2%20(%E7%82%BC%E9%93%9C%E5%AD%A6%E9%99%A2)/live2d/11310 , download files to local and use like this (only modify the model path.):
```
import { ref, onMounted } from "vue";
import { Live2DModel } from 'pixi-live2d-display-lipsyncpatch';

const model = ref(null)
const init = async (modelName) => {
  const fileMap = {
    person_1: "/src/assets/live2d/11310/Lead_00.model.json",
  };
  const modelPath = fileMap[modelName]
  const pixi = window.PIXI;
  // const live2d = pixi.live2d;
  const app = new pixi.Application({
    view: document.getElementById("live2dCvs"),
    autoStart: true,
    resizeTo: window,
    backgroundColor: 0x333333,
    opacity: 0,
    transparent: true,
  });

  model.value = await Live2DModel.from(modelPath);
  app.stage.addChild(model.value);

  const scaleX = innerWidth / model.value.width;
  const scaleY = innerHeight / model.value.height;
  // fit the window
  model.value.scale.set(Math.min(scaleX, scaleY));

  model.value.y = (innerHeight - model.value.height) * 0.5;
  model.value.x = (innerWidth - model.value.width) * 0.5;

  console.log(model.value)
};

const speak = (audio_link) => {
  return new Promise((resolve, reject) => {
    var volume = 1; // [Optional arg, can be null or empty] [0.0 - 1.0]
    var expression = 4; // [Optional arg, can be null or empty] [index|name of expression]
    var resetExpression = true; // [Optional arg, can be null or empty] [true|false] [default: true] [if true, expression will be reset to default after animation is over]
    var crossOrigin = "anonymous"; // [Optional arg, to use not same-origin audios] [DEFAULT: null]

    model.value.speak(audio_link, {
      volume: volume, expression:expression, resetExpression:resetExpression, crossOrigin: crossOrigin,
      onFinish: () => resolve('voice finished'),
      onError: (error) => reject(error)
    })

  })
}
```

when I call `init()`, it throw the error `Unknown settings format.`

<img width="824" alt="image" src="https://github.com/user-attachments/assets/656021f9-875c-4282-8b58-2e1a3daec717">

here is the context.source:

<img width="837" alt="image" src="https://github.com/user-attachments/assets/2fa32556-df88-46df-945d-1d955dcbd902">

I found this model can loaded from https://guansss.github.io/live2d-viewer-web, and it has a motion that say something while touch. Any idea about why thorw this error?

**Comment by RaSan147** [comment]
Interesting, since it works on guansss demo site, I'll check n see if theres any issue on my end. I actually didn't touch the loader and settings api. So can't guarantee I can find a solution. Can you try with the original repo code with same model?

**Comment by weihaopeng** [comment]
> original repo code

You means using this package? https://github.com/guansss/pixi-live2d-display

**Comment by RaSan147** [comment]
Yes, this is just a fork of that one. Try and let me know. If doesn't work,
we can send the issue to there (I'll also try to fix)

**Comment by weihaopeng** [comment]
Okay.

**Comment by weihaopeng** [comment]
@RaSan147 I found how to resolve it, but didn't know why.

The origin model.json file didn't have `"version": "Sample 1.0.0"`. After I added it manually, it can run.

I don't use Live2D a lot, maybe you know the reason for this?

* Before
* ```{
  "type": "Live2D Model Setting",
  "name": "千竹婚纱",
  "model": "Lead_00.moc",
  "textures": {
    "11310": ["texture_00.png", "texture_01.png"]
  },
  ... other params
  ````

* After
* ```{
  "version": "Sample 1.0.0",
  "type": "Live2D Model Setting",
  "name": "千竹婚纱",
  "model": "Lead_00.moc",
  "textures": ["textures/texture_00.png", "textures/texture_01.png"],
  ... other params
  ````

**Comment by RaSan147** [comment]
Absolutely no idea buddy. Maybe export glitch. All the models json have that.

**Comment by weihaopeng** [comment]
Anyway, thanks!
