### ISSUE TITLE
model.speak doesn't work.

### ISSUE THREAD

**Issue by ShionSeal** [RaSan147/pixi-live2d-display#4]
I'm trying to use a model.speak() by following your code(Lipsync Only), but the Live2D model doesn't do lipsync and output the content of audio file.
How can I fix this problem.

Error code is this:Uncaught (in promise) TypeError: model.speak is not a function

`{
  "name": "live2d",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.2.0"
  },
  "dependencies": {
    "pixi-live2d-display": "^0.4.0",
    "pixi.js": "^6.5.10"
  }
}
`

**Comment by RaSan147** [comment]
Are you using the npm or cdn version... Npm is not supported.

Use thos version only until npm is officially supported
https://github.com/RaSan147/pixi-live2d-display#via-cdn-lipsync-patched

**Comment by ShionSeal** [comment]
I appreciate your quick response.

I'm using both npm such as import { Live2DModel, ModelSettings } from 'pixi-live2d-display'; and cdn which you suggest me in html.
Does that cause a problem?

Just in case I want you see my codes which I created.
html and html.

`<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/pixi.js@6.5.2/dist/browser/pixi.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/RaSan147/pixi-live2d-display@v0.4.0-ls-2/dist/index.min.js"></script>
  <title>Live2D</title>
</head>

<body>
  <div id="app"></div>
  <canvas id="Model"></canvas>
  <script type="module" src="/main.js"></script>
</body>

</html>`

`import * as PIXI from 'pixi.js';
import { Live2DModel } from 'pixi-live2d-display';

// expose PIXI to window so that this plugin is able to
// reference window.PIXI.Ticker to automatically update Live2D models
window.PIXI = PIXI;

(async function () {
  const app = new PIXI.Application({
    view: document.getElementById('Model'),
    autoStart: true,
    backgroundAlpha: 0,
    backgroundColor: 0x0000ff,
    resizeTo: window
  });

  const model = await Live2DModel.from('./Hiyori/Hiyori.model3.json', { autoInteract: false });

  // transforms
  model.rotation = Math.PI;
  model.skew.x = Math.PI;
  model.scale.set(0.45);
  model.anchor.set(0.5, 0.5);
  model.position.set(window.innerWidth / 2, window.innerHeight / 0.85);
  app.stage.addChild(model);

  // background
  let backgroundTexture = await PIXI.Texture.from('./test_picture.jpg');
  let background = new PIXI.Sprite(backgroundTexture);
  background.anchor.set(0.5);
  background.x = app.screen.width / 2;
  background.y = app.screen.height / 2;
  background.width = app.screen.width;
  background.height = app.screen.height;
  app.stage.addChildAt(background, 0); // Add the background first

  var audio_link = "https://cdn.jsdelivr.net/gh/RaSan147/pixi-live2d-display@v1.0.3/playground/test.mp3" // [relative or full url path] [mp3 or wav file]
  var volume = 1; // [Optional arg, can be null or empty] [0.0 - 1.0]
  var expression = 4; // [Optional arg, can be null or empty] [index|name of expression]
  var resetExpression = true; // [Optional arg, can be null or empty] [true|false] [default: true] [if true, expression will be reset to default after animation is over]

  model.speak(audio_link, { volume: volume, expression: expression, resetExpression: resetExpression })

  // Or if you want to keep some things default
  model.speak(audio_link)
  model.speak(audio_link, { volume: volume })
  model.speak(audio_link, { expression: expression, resetExpression: resetExpression })
})();`

**Comment by ShionSeal** [comment]
Oh.... sorry I made a mistake.
html and js

**Comment by RaSan147** [comment]
![image](https://github.com/RaSan147/pixi-live2d-display/assets/34002411/a5a96936-d9d7-4451-a79e-c983b24379f3)
as you can see, 1st its loading from the CDN
but later its getting overwritten by the NPM (unsupported version)
so it won't work. kindly comment out the NPM version (its under work with major changes) 
sorry didn't remove that import statements from example...

**Comment by ShionSeal** [comment]
I tried the code which you gave me.
Moreover, I changed the way to load Live2Dmodel as this:
const model = await PIXI.live2d.Live2DModel.from('./Hiyori/Hiyori.model3.json', { autoInteract: false });
As a result, new problem occurred.
Erro code:Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Live2DModel')

**Comment by ShionSeal** [comment]
The error which I told you above was fixed that the path of live2d model wasn't correct.
I'm sorry for the inconvenience.

However, I got extra errors.
index.min.js:1  The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
[SoundManager] Error occurred on "https://cdn.jsdelivr.net/gh/RaSan147/pixi-live2d-display@v1.0.3/playground/test.mp3" DOMException: play() failed because the user didn't interact with the document first.
[MotionManager(Hiyori)] Failed to play audio  DOMException: play() failed because the user didn't interact with the document first.

**Comment by RaSan147** [comment]
It is a browser safety, browser doesn't allow auto play if the display was
untouched, easy walk around is either manually/js clicking something (that
doesn't fire an on click event)
And don't apologize buddy, its the issue page, we also faced similar issues
in life.

**Comment by ShionSeal** [comment]
Finally, model.speak and its lipsync worked!!!
Thank you very much!!!
