### ISSUE TITLE
Can the lipsync effect be achieved without motion

### ISSUE THREAD

**Issue by finger92** [RaSan147/pixi-live2d-display#6]
I try to add lipsync function to a public model (https://www.youtube.com/watch?v=E81d7iSEjcA). However, it doesn't have any motions. Is there any way to add lipsync to it?

**Comment by RaSan147** [comment]
ok thats a great thing you mentioned, i'll look into it
*sorry for the late reply (didn't get any notification)

**Comment by RaSan147** [comment]
i'll try to make a separate function that can do lip-syncing without interacting the motion

**Comment by RaSan147** [comment]
fixed in verision 1.0.3

please use updated CDN link

**Comment by RaSan147** [comment]
use `model.speak("link.to/audio.mp3")

closing this issue
