### ISSUE TITLE
how to fix this,it can't play in chrome

### ISSUE THREAD

**Issue by Xiobio** [RaSan147/pixi-live2d-display#6]
MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://cdn.jsdelivr.net/gh/RaSan147/pixi-live2d-display@v1.0.3/playground/test.mp3

**Comment by RaSan147** [comment]
There is a crossOrigin
param there.
You need to set that to
crossOrigin = "anonymous"

Will update the docs ASAP

**Comment by Xiobio** [comment]
if i tatally use this in html file ,how should i  add the setting of 'crossOrigin = "anonymous"‘ in <script></script> ？thank you

**Comment by RaSan147** [comment]
Check the updated doc and let me know

https://github.com/RaSan147/pixi-live2d-display/blob/master/README.md#fix-mediaelementaudiosource-outputs-zeroes-due-to-cors-access-restrictions-for

**Comment by Xiobio** [comment]
many thanks ,it fix

**Comment by RaSan147** [comment]
Thanks for reminding me.
Closing the issue
