### ISSUE TITLE
How to install with npm?

### ISSUE THREAD

**Issue by xiaoqiang1999** [RaSan147/pixi-live2d-display#9]
Thank the author for his open source.
Next is the question:
Has this package been published on npm?

**Comment by RaSan147** [comment]
I submitted the pr to the original authon. He had diffent thoughts rather than simple functional steps.
He updated the code but didn't merge yet. Lets just he jumps back to coding and merge
(I don't know how and have the permission to post in npm)

**Comment by xiaoqiang1999** [comment]
> I submitted the pr to the original authon. He had diffent thoughts rather than simple functional steps. He updated the code but didn't merge yet. Lets just he jumps back to coding and merge (I don't know how and have the permission to post in npm)

I see that you submitted the code to the original author, but he seems too busy to maintain it.

But you can use your own npm account to publish this branch's npm package.

At the same time, I found a package on NPM, which seems to be released based on your branch:
[pixi-live2d-display-lip-sync](https://www.npmjs.com/package/pixi-live2d-display-lip-sync)
Therefore, it is recommended that you use your own account to publish one. After all, it is the fruit of your own labor.

**Comment by RaSan147** [comment]
Will do asap, thanks a lot...
Also thanks for notifying me.

**Comment by RaSan147** [comment]
Done, kindly test, idk how to test node modules... (i'm a python person)

**Comment by xiaoqiang1999** [comment]
> Done, kindly test, idk how to test node modules... (i'm a python person)

I conducted basic tests, and the rendering works normally, You can continue testing.
Git clone this project: [xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch](https://github.com/xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch)

Install dependencies and run the project (requires Node.js 18+) : 
```shell
  cd test-pixi-live2d-display-lipsyncpatch
  npm install
  npm run dev
```

Now you can happily test it!

**Comment by xiaoqiang1999** [comment]
> 完成，亲切地测试，idk 如何测试节点模块......（我是Python人）

Also, thanks for the work you do, this is great work.

**Comment by RaSan147** [comment]
> > Done, kindly test, idk how to test node modules... (i'm a python person)
> 
> I conducted basic tests, and the rendering works normally, You can continue testing. Git clone this project: [xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch](https://github.com/xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch)
> 
> Install dependencies and run the project (requires Node.js 18+) :
> 
> ```shell
>   cd test-pixi-live2d-display-lipsyncpatch
>   npm install
>   npm run dev
> ```
> 
> Now you can happily test it!

Thanks a lot🥰

**Comment by RaSan147** [comment]
> > 完成，亲切地测试，idk 如何测试节点模块......（我是Python人）
> 
> Also, thanks for the work you do, this is great work.

Necessity my friend, made me learn TS from JS structure 😅.
You're welcome 😇

**Comment by RaSan147** [comment]
Closing the issue

**Comment by xiaoqiang1999** [comment]
After testing, I found a bug: 
after the speak() function is called, the audio starts to play, but it automatically stops after playing for a period of time,  and no events will be triggered, and when the speak() function is called again, it is found that the speak() function is invalid.
This bug only occurs in npm packages, and the introduction of script tags is normal.
Very strange bug.
At the same time, I updated the test project, which can reproduce this bug: [xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch](https://github.com/xiaoqiang1999/test-pixi-live2d-display-lipsyncpatch)

**Comment by RaSan147** [comment]
Thanks a lot, checking...

**Comment by RaSan147** [comment]
Fixed, removed some code thinking user will handle it (that disables other motions if audio playing)
Reverted it.

![image](https://github.com/user-attachments/assets/3d4277d6-af2b-4bfb-bee0-be77084c7caf)

**Comment by RaSan147** [comment]
Use 

```
  "dependencies": {
    "pixi-live2d-display-lipsyncpatch": "^0.5.0-ls-7",
    "pixi.js": "^7.4.2"
  }
}
```

**Comment by xiaoqiang1999** [comment]
Just tested, this bug has been fixed! Amazing work speed 👍.
Thank you for your contribution to the front-end ecosystem.

**Comment by RaSan147** [comment]
Great... My bad😅, feature turned bug. Thanks.
